version: '3.6'

services:
  postgres:
    container_name: db-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres